Update instrument.cc
When compile stage I have faced a problem as follows:
instrument.cc: In function ‘void bx_instr_lin_access(unsigned int, bx_address, bx_address, unsigned int, unsigned int, unsigned int)’:
instrument.cc:416:85: error: ‘struct bx_gen_reg_t’ has no member named ‘rrx’
     bool dst_in_kernel = windows::check_kernel_addr(pcpu->gen_reg[BX_32BIT_REG_EDI].rrx);
                                                                                     ^
instrument.cc:417:85: error: ‘struct bx_gen_reg_t’ has no member named ‘rrx’
     bool src_in_kernel = windows::check_kernel_addr(pcpu->gen_reg[BX_32BIT_REG_ESI].rrx);
                                                                                     ^
Makefile:66: recipe for target 'instrument.o' 

Because Bochs wouldn't use "rrx" suffix/member in x86 mode. I have changed it to "dword.erx" to access 32-bit registers.